[jenkins_master]
jenkins-master-vm ansible_host=35.240.205.253 ansible_user=opsadmin ansible_ssh_private_key_file=../admin-key

[jenkins_agent]
calculator-app ansible_host=34.142.200.92 ansible_user=opsadmin ansible_ssh_private_key_file=../admin-key